## Longest Plateau
### Problem statement
Given a `numpy array` of integers, find the length and location of the longest contiguous sequence of equal values where the values of the elements just before and just after this sequence are smaller.

### Implementation details
#### Function signature
Write a function that accepts an array as input. The function should return three integers:
* starting index of longest plateau.
* ending index (plus one) of the longest plateau.
* length of the longest plateau.

#### Example
For example, if the array is (with indices below for convenience):

[1 1 1 1 1 1 2 3 2 3 2 3 3 3 3 3 3 1 1 2]

   0  1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9

the function should return (start, stop, length):

(11, 17, 6)

Note that because we do not know what comes before the 1 at position 0, it is not a plateau.

Let's agree that we'll return the first instance in the case of a tie.

#### Testing

For testing include a optional arguement to your function called display. By default it should be false. If it is true, then the longest plateau will be displayed as follows:

[1 1 1 1 1 1 2 3 2 3 2 3 3 3 3 3 3 1 1 2]

                  s------e
 
(Note printing is strange with Jupyter notebooks s under the first member, e under the last, and dashes under the rest.)


#### Hints

* Find differences between neighboring positions in `numpy` arrays
* no difference is a plateau
* positive difference is up to a plateau
* negative difference is down off the plateau
* look for the pattern up, plateau, down.
* use test data from `randint`, see below

In [1]:
from pylab import randint
a = randint(1,4,20) # Start, stop+1, number of samples...
print(a)

[3 2 2 1 1 3 3 3 3 3 1 1 1 3 1 3 3 1 3 3]


In [2]:
def l_plat(ary):
    end,start=0,0
    gend,gstart=0,0
    glength=0
    for i in range(0,len(ary)-1):
        if ary[i]==ary[i+1]:
            start=i
            end=i+1
            while ary[start]==ary[end]:
                end+=1
                if end+1>len(ary): #we break if before have gone too far
                    break
            if (end-start)>(gend-gstart): #if current length is longer then we reassign what the longest is
                gend,gstart=end,start
                glength=gend-gstart
    return(gstart,gend-1,glength)

l_plat(a)

(5, 9, 5)

### Final test
To demonstrate your function works, print the longest plaeau of the following arrays. 

In [3]:
from numpy import array
a1 = array([1, 4, 3, 2, 1, 2, 0, 3, 2, 3, 1, 3, 0, 1, 4, 0, 0, 1, 3, 3, 0, 2, 5, 5,\
    0, 4, 3, 3, 0, 1, 4, 4, 3, 0, 5, 2, 2, 3, 2, 4, 5, 5, 5, 5, 0, 4, 3, 1, 2, 1,\
    5, 4, 0, 4, 3, 2, 5, 1, 5, 0, 3, 3, 2, 4, 1, 4, 0, 5, 4, 5, 3, 3, 5, 2, 0,\
    3, 3, 0, 1, 1, 0, 0, 5, 0, 0, 5, 0, 0, 4, 5, 2, 2, 1, 0, 5, 1, 3, 5, 5, 1])

a2 = array([0, 2, 1, 0, 2, 1, 1, 2, 5, 2, 0, 0, 0, 0, 2, 1, 0, 4, 2, 3, 1, 1, 4, 0,\
    2, 1, 3, 2, 0, 0, 3, 0, 5, 2, 0, 1, 5, 0, 3, 4, 4, 1, 0, 4, 4, 4, 1, 4, 3, 5,\
    3, 1, 4, 4, 3, 0, 1, 0, 1, 3, 1, 2, 2, 1, 2, 3, 4, 5, 3, 0, 1, 2, 2, 1, 0,\
    5, 5, 3, 2, 4, 0, 4, 3, 2, 0, 0, 0, 5, 5, 4, 3, 4, 0, 4, 1, 0, 4, 3, 5, 1])

a3 = array([3, 3, 4, 5, 0, 4, 0, 4, 5, 0, 2, 1, 0, 5, 3, 0, 3, 5, 0, 1, 1, 3, 3, 3, \
     4, 3, 5, 3, 0, 5, 4, 0, 2, 1, 3, 0, 2, 2, 4, 3, 4, 0, 1, 4, 2, 5, 0, 1, 1, 2,\
    1, 4, 1, 1, 4, 2, 0, 3, 2, 1, 3, 0, 5, 5, 1, 2, 1, 1, 3, 3, 2, 1, 5, 3, 1,\
    3, 5, 3, 4, 1, 3, 4, 2, 4, 4, 2, 5, 0, 0, 0, 1, 1, 4, 0, 2, 4, 4, 3, 1, 3])

a4 = array([1, 1, 1, 2, 1, 1, 3, 2, 2, 3, 1, 3, 3, 3, 3, 3, 1, 3, 1, 2, 1, 3, 3, 3, 2])


In [4]:
print(l_plat(a1))
print(l_plat(a2))
print(l_plat(a3))

(40, 43, 4)
(10, 13, 4)
(21, 23, 3)
